<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	 <xacro:property name="chassis_length" value="0.2"/>
    <xacro:property name="chassis_width" value="0.2"/>
    <xacro:property name="chassis_height" value="0.01"/>
    <xacro:property name="chassis_mass" value="1.0"/>
	<xacro:property name="chassis_base_offset" value='0.1'>
    <xacro:property name="wheel_radius" value="0.045"/>
    <xacro:property name="wheel_thickness" value="0.01"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset" value="0.0925"/>
    <xacro:property name="caster_wheel_radius" value="wheel_radius-chassis base_offset"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${-chassis_base_offset}"/>

	<xacro:include filename="inertial_macros.xacro" />
	<material name="white">
		<color rgba="1 1 1 1" />
	</material>
	<material name="orange">
		<color rgba="1 0.3 0.1 1" />
	</material>
	<material name="blue">
		<color rgba="0.2 0.2 1 1" />
	</material>
	<material name="black">
		<color rgba="0 0 0 1" />
	</material>
	<!-- BASE LINK -->
	<link name="base_link">
	</link>
	<joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>
	<!-- CHASSIS -->
	<joint name="chassis_joint" type="fixed">
		<parent link="base_link" />
		<child link="chassis" />
		<origin xyz="0 0 0" />
	</joint>
	<link name="chassis">
		<visual>
			<origin yz="0 0 ${chassis_height/2 - chassis_base_offset}" rpy="0 0 0" />
			<geometry>
				 <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
			</geometry>
			<material name="white" />
		</visual>
		<collision>
			<origin yz="0 0 ${chassis_height/2 - chassis_base_offset}" rpy="0 0 0" />
			<geometry>
				 <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
			</geometry>
		</collision>
		<xacro:inertial_box mass="0.5" x="0.25" y="0.25" z="0.12">
			<origin xyz="0 0 ${chassis_height/2 - chassis_base_offset}" rpy="0 0 0" />
		</xacro:inertial_box>
	</link>
	<gazebo reference="chassis">
		<material>
			Gazebo/White
		</material>
	</gazebo>
	<!-- LEFT WHEEL -->
	<joint name="left_wheel_joint" type="continuous">
		<parent link="base_link" />
		<child link="left_wheel" />
		<origin xyz="0 ${wheel_offset} 0" rpy="-${pi/2} 0 0" />
		<axis xyz="0 0 1" />
	</joint>
	<link name="left_wheel">
		<visual>
			<geometry>
				<cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
			</geometry>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<sphere radius="${wheel_radius}" />
			</geometry>
		</collision>
		<xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
			<origin xyz="0 0 0" rpy="0 0 0" />
		</xacro:inertial_cylinder>
	</link>
	<gazebo reference="left_wheel">
		<material>
			Gazebo/Blue
		</material>
	</gazebo>
	<!-- RIGHT WHEEL -->
	<joint name="right_wheel_joint" type="continuous">
		<parent link="base_link" />
		<child link="right_wheel" />
		<origin xyz="0 ${-wheel_offset} 0" rpy="${pi/2} 0 0" />
		<axis xyz="0 0 -1" />
	</joint>
	<link name="right_wheel">
		<visual>
			<geometry>
				<cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
			</geometry>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<sphere radius="${wheel_radius}"/>
			</geometry>
		</collision>
		<xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
			<origin xyz="0 0 0" rpy="0 0 0" />
		</xacro:inertial_cylinder>
	</link>
	<gazebo reference="right_wheel">
		<material>
			Gazebo/Blue
		</material>
	</gazebo>
	<!-- FRONT CASTER -->
	<joint name="front_caster_wheel_joint" type="fixed">
		<parent link="chassis" />
		<child link="front_caster_wheel" />
		<origin xyz="${caster_offset_x} 0 ${caster_offset_z}" rpy="0 0 0" />
	</joint>
	<link name="front_caster_wheel">
		<visual>
			<geometry>
				<sphere radius="${caster_radius}" />
			</geometry>
			<material name="black" />
		</visual>
		<collision>
			<geometry>
				<sphere radius="${caster_radius}"  />
			</geometry>r
		</collision>
		<xacro:inertial_sphere mass="0.1" radius="${caster_radius}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_sphere>
	</link>
	<gazebo reference="front_caster_wheel">
		<material>
			Gazebo/Black
		</material>
		<mu1 value="0.001" />
		<mu2 value="0.001" />
	</gazebo>
	<!-- BACK CASTER -->
	<joint name="back_caster_wheel_joint" type="fixed">
		<parent link="chassis" />
		<child link="back_caster_wheel" />
		<origin xyz="${-caster_offset_x} 0 ${caster_offset_z}" rpy="0 0 0" />
	</joint>
	<link name="back_caster_wheel">
		<visual>
			<geometry>
				<sphere radius="${caster_radius}" />
			</geometry>
			<material name="black" />
		</visual>
		<collision>
			<geometry>
				<sphere radius="${caster_radius}" />
			</geometry>
		</collision>
		<xacro:inertial_sphere mass="0.1" radius="${caster_radius}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_sphere>
	</link>
	<gazebo reference="back_caster_wheel">
		<material>
			Gazebo/Black
		</material>
		<mu1 value="0.001" />
		<mu2 value="0.001" />
	</gazebo>
</robot>

